name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH || true
          echo "$HOME/.local/bin" >> $GITHUB_PATH || true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Create venv and install
        run: |
          uv venv
          uv run pip install -e .[dev]
      - name: Run tests
        run: uv run pytest -q
      - name: Build docs
        run: uv run sphinx-build -b html docs docs/_build/html


